### ISSUE TITLE
Code wont work on different machine

### ISSUE THREAD

**Issue by yanagicode** [yanagicode/codepath-calculatip#1]
Code works fine on my machine (Winows 10 - Bitnami WAMP), but it didn't worked on different machine.

Error:
```
Notice: Undefined variable: error1 in C:\wamp64\www\codepath-calculatip\Calculatip\index.php on line 54 Call Stack #TimeMemoryFunctionLocation 10.0005265264{main}()...\index.php:0">Bill subtotal:
```

**Comment by yanagicode** [comment]
Fixed after adding this line inside first ```php``` where I assign flags for error1, 2, and 3,  
```php
$error1 = $error2 = $error3 = 0;
```

**Comment by codepathreview** [comment]
Great work!! This exercise is intended in part to give you an introduction to the general rhythm of this course. The course is entirely project-based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer learn the practical elements of Web Security and best practices as quickly as possible. We also do a code review for each submitted project once the program begins.

Great to see you were able to complete a large number of optional features to your app already. Your project looks great. As you can probably tell, the optional features available on each project are a great vehicle for exploring the development wit PHP.

We'll be following up with you again shortly to outline the next steps in the admissions process.
